// src/components/SettingsPanel.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useProgressStore } from '../stores/progressStore';
import { LanguageSelector } from './LanguageSelector';
import './SettingsPanel.css';

interface SettingsPanelProps {
  onClose: () => void;
  isStandalone?: boolean;
}

export function SettingsPanel({ onClose, isStandalone = false }: SettingsPanelProps) {
  const { t } = useTranslation();
  const {
    settings,
    setLanguage,
    setTheme,
    setFontSize,
    setOpacity,
    setAlwaysOnTop,
    setAutoStart,
    setNotifications,
    setSound,
    setSoundVolume,
    setHttpPort,
    setCustomColors,
    setReminderThreshold,
    setDoNotDisturb,
    setDoNotDisturbStart,
    setDoNotDisturbEnd,
    clearHistory,
    history
  } = useProgressStore();
  const [activeTab, setActiveTab] = useState<'general' | 'appearance' | 'notifications' | 'tasks' | 'shortcuts'>('general');
  const [showImportExport, setShowImportExport] = useState(false);

  const handleExportConfig = () => {
    const config = {
      settings: {
        theme: settings.theme,
        opacity: settings.opacity,
        alwaysOnTop: settings.alwaysOnTop,
        notifications: settings.notifications,
        sound: settings.sound,
        soundVolume: settings.soundVolume,
        httpPort: settings.httpPort,
        customColors: settings.customColors,
        reminderThreshold: settings.reminderThreshold,
        doNotDisturb: settings.doNotDisturb,
        doNotDisturbStart: settings.doNotDisturbStart,
        doNotDisturbEnd: settings.doNotDisturbEnd,
      },
      history: history.slice(0, 20),
      exportedAt: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'vibe-progress-config.json';
    a.click();
    URL.revokeObjectURL(url);
    setShowImportExport(false);
  };

  const handleImportConfig = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const config = JSON.parse(event.target?.result as string);
        if (config.settings) {
          if (config.settings.theme) setTheme(config.settings.theme);
          if (config.settings.fontSize) setFontSize(config.settings.fontSize);
          if (config.settings.opacity) setOpacity(config.settings.opacity);
          if (config.settings.alwaysOnTop !== undefined) setAlwaysOnTop(config.settings.alwaysOnTop);
          if (config.settings.notifications !== undefined) setNotifications(config.settings.notifications);
          if (config.settings.sound !== undefined) setSound(config.settings.sound);
          if (config.settings.soundVolume) setSoundVolume(config.settings.soundVolume);
          if (config.settings.httpPort) setHttpPort(config.settings.httpPort);
          if (config.settings.customColors) setCustomColors(config.settings.customColors);
          if (config.settings.reminderThreshold) setReminderThreshold(config.settings.reminderThreshold);
          if (config.settings.doNotDisturb !== undefined) setDoNotDisturb(config.settings.doNotDisturb);
          if (config.settings.doNotDisturbStart) setDoNotDisturbStart(config.settings.doNotDisturbStart);
          if (config.settings.doNotDisturbEnd) setDoNotDisturbEnd(config.settings.doNotDisturbEnd);
        }
        setShowImportExport(false);
      } catch (error) {
        console.error('Failed to import config:', error);
        alert('Failed to import configuration. Please check the file format.');
      }
    };
    reader.readAsText(file);
  };

  if (isStandalone) {
    return (
      <div className="settings-panel standalone" onClick={e => e.stopPropagation()}>
        {/* No header for standalone window as it has system title bar */}
        {renderContent()}
      </div>
    );
  }

  return (
    <div className="settings-overlay" onClick={onClose}>
      <div className="settings-panel" onClick={e => e.stopPropagation()}>
        <div className="settings-header">
          <h2>{t('settings.title')}</h2>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>
        {renderContent()}
      </div>
    </div>
  );

  function renderContent() {
    return (
      <>
        <div className="settings-tabs">
          <button
            className={`tab ${activeTab === 'general' ? 'active' : ''}`}
            onClick={() => setActiveTab('general')}
          >
            {t('settings.tabs.general')}
          </button>
          <button
            className={`tab ${activeTab === 'appearance' ? 'active' : ''}`}
            onClick={() => setActiveTab('appearance')}
          >
            {t('settings.tabs.appearance')}
          </button>
          <button
            className={`tab ${activeTab === 'notifications' ? 'active' : ''}`}
            onClick={() => setActiveTab('notifications')}
          >
            {t('settings.tabs.notifications')}
          </button>
          <button
            className={`tab ${activeTab === 'tasks' ? 'active' : ''}`}
            onClick={() => setActiveTab('tasks')}
          >
            {t('settings.tabs.tasks')}
          </button>
          <button
            className={`tab ${activeTab === 'shortcuts' ? 'active' : ''}`}
            onClick={() => setActiveTab('shortcuts')}
          >
            {t('settings.tabs.shortcuts')}
          </button>
        </div>

        <div className="settings-content">
          {activeTab === 'general' && (
            <div className="settings-section">
              <LanguageSelector />
              <div className="setting-item">
                <label>{t('settings.general.autoStart')}</label>
                <input
                  type="checkbox"
                  checked={settings.autoStart}
                  onChange={e => setAutoStart(e.target.checked)}
                />
              </div>
              <div className="setting-item">
                <label>{t('settings.general.alwaysOnTop')}</label>
                <input
                  type="checkbox"
                  checked={settings.alwaysOnTop}
                  onChange={e => setAlwaysOnTop(e.target.checked)}
                />
              </div>
              <div className="setting-item">
                <label>{t('settings.general.httpPort')}</label>
                <input
                  type="number"
                  className="http-input"
                  value={settings.httpPort}
                  onChange={e => setHttpPort(parseInt(e.target.value) || 31415)}
                  min="1024"
                  max="65535"
                />
              </div>
              <div className="setting-item">
                <label>{t('settings.general.configManagement')}</label>
                <button className="action-btn" onClick={() => setShowImportExport(true)}>
                  {t('settings.general.manage')}
                </button>
              </div>
            </div>
          )}

          {activeTab === 'appearance' && (
            <div className="settings-section">
              <div className="setting-item">
                <label>{t('settings.appearance.theme')}</label>
                <select
                  value={settings.theme}
                  onChange={e => setTheme(e.target.value as 'dark' | 'light' | 'purple' | 'ocean' | 'forest' | 'midnight')}
                >
                  <option value="dark">{t('settings.appearance.themeOptions.dark')}</option>
                  <option value="light">{t('settings.appearance.themeOptions.light')}</option>
                  <option value="purple">{t('settings.appearance.themeOptions.purple')}</option>
                  <option value="ocean">{t('settings.appearance.themeOptions.ocean')}</option>
                  <option value="forest">{t('settings.appearance.themeOptions.forest')}</option>
                  <option value="midnight">{t('settings.appearance.themeOptions.midnight')}</option>
                </select>
              </div>
              <div className="setting-item">
                <label>{t('settings.appearance.fontSize', { size: settings.fontSize })}</label>
                <input
                  type="range"
                  min="10"
                  max="24"
                  step="1"
                  value={settings.fontSize}
                  onChange={e => setFontSize(parseInt(e.target.value))}
                />
              </div>
              <div className="setting-item">
                <label>{t('settings.appearance.opacity', { percentage: Math.round(settings.opacity * 100) })}</label>
                <input
                  type="range"
                  min="0.3"
                  max="1"
                  step="0.05"
                  value={settings.opacity}
                  onChange={e => setOpacity(parseFloat(e.target.value))}
                />
              </div>
              <div className="setting-item">
                <label>{t('settings.appearance.customPrimaryColor')}</label>
                <div className="color-input-wrapper">
                  <input
                    type="color"
                    value={settings.customColors.primaryColor || '#6366f1'}
                    onChange={e => setCustomColors({ primaryColor: e.target.value })}
                    className="color-input"
                  />
                  <input
                    type="text"
                    className="color-text-input"
                    value={settings.customColors.primaryColor || ''}
                    onChange={e => setCustomColors({ primaryColor: e.target.value })}
                    placeholder="#6366f1"
                  />
                </div>
              </div>
              <div className="setting-item">
                <label>{t('settings.appearance.customBackground')}</label>
                <div className="color-input-wrapper">
                  <input
                    type="color"
                    value={settings.customColors.backgroundColor || '#0f172a'}
                    onChange={e => setCustomColors({ backgroundColor: e.target.value })}
                    className="color-input"
                  />
                  <input
                    type="text"
                    className="color-text-input"
                    value={settings.customColors.backgroundColor || ''}
                    onChange={e => setCustomColors({ backgroundColor: e.target.value })}
                    placeholder="#0f172a"
                  />
                </div>
              </div>
              <div className="setting-item">
                <label>{t('settings.appearance.resetColors')}</label>
                <button
                  className="action-btn small"
                  onClick={() => setCustomColors({ primaryColor: '', backgroundColor: '', textColor: '' })}
                >
                  {t('settings.appearance.reset')}
                </button>
              </div>
            </div>
          )}

          {activeTab === 'notifications' && (
            <div className="settings-section">
              <div className="setting-item">
                <label>{t('settings.notifications.desktopNotifications')}</label>
                <input
                  type="checkbox"
                  checked={settings.notifications}
                  onChange={e => setNotifications(e.target.checked)}
                />
              </div>
              <div className="setting-item">
                <label>{t('settings.notifications.soundAlerts')}</label>
                <input
                  type="checkbox"
                  checked={settings.sound}
                  onChange={e => setSound(e.target.checked)}
                />
              </div>
              {settings.sound && (
                <div className="setting-item indent">
                  <label>{t('settings.notifications.volume', { percentage: Math.round(settings.soundVolume * 100) })}</label>
                  <input
                    type="range"
                    min="0"
                    max="1"
                    step="0.1"
                    value={settings.soundVolume}
                    onChange={e => setSoundVolume(parseFloat(e.target.value))}
                  />
                </div>
              )}
              <div className="setting-item">
                <label>{t('settings.notifications.completionThreshold', { percentage: settings.reminderThreshold })}</label>
                <input
                  type="range"
                  min="50"
                  max="100"
                  step="5"
                  value={settings.reminderThreshold}
                  onChange={e => setReminderThreshold(parseInt(e.target.value))}
                />
              </div>
              <div className="setting-item">
                <label>{t('settings.notifications.doNotDisturb')}</label>
                <input
                  type="checkbox"
                  checked={settings.doNotDisturb}
                  onChange={e => setDoNotDisturb(e.target.checked)}
                />
              </div>
              {settings.doNotDisturb && (
                <>
                  <div className="setting-item indent">
                    <label>{t('settings.notifications.startTime')}</label>
                    <input
                      type="time"
                      value={settings.doNotDisturbStart}
                      onChange={e => setDoNotDisturbStart(e.target.value)}
                      className="time-input"
                    />
                  </div>
                  <div className="setting-item indent">
                    <label>{t('settings.notifications.endTime')}</label>
                    <input
                      type="time"
                      value={settings.doNotDisturbEnd}
                      onChange={e => setDoNotDisturbEnd(e.target.value)}
                      className="time-input"
                    />
                  </div>
                </>
              )}
            </div>
          )}

          {activeTab === 'tasks' && (
            <div className="settings-section">
              <div className="setting-item">
                <label>{t('settings.tasks.history')}</label>
                <span className="info-text">{t('settings.tasks.historyCount', { count: history.length })}</span>
              </div>
              <div className="setting-item">
                <label>{t('settings.tasks.clearHistory')}</label>
                <button
                  className="action-btn danger small"
                  onClick={clearHistory}
                >
                  {t('settings.tasks.clear')}
                </button>
              </div>
            </div>
          )}

          {activeTab === 'shortcuts' && (
            <div className="settings-section">
              <div className="shortcuts-info">
                <h4>{t('settings.shortcuts.title')}</h4>
                <p>{t('settings.shortcuts.description')}</p>
                <div className="shortcut-list">
                  <div className="shortcut-item">
                    <span className="shortcut-key">{t('settings.shortcuts.rightClick')}</span>
                    <span className="shortcut-desc">Open context menu</span>
                  </div>
                  <div className="shortcut-item">
                    <span className="shortcut-key">{t('settings.shortcuts.drag')}</span>
                    <span className="shortcut-desc">Move window</span>
                  </div>
                  <div className="shortcut-item">
                    <span className="shortcut-key">{t('settings.shortcuts.scroll')}</span>
                    <span className="shortcut-desc">Adjust progress</span>
                  </div>
                  <div className="shortcut-item">
                    <span className="shortcut-key">{t('settings.shortcuts.clickStatus')}</span>
                    <span className="shortcut-desc">Activate IDE window</span>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {showImportExport && (
          <div className="import-export-modal">
            <div className="modal-content">
              <h3>{t('settings.importExport.title')}</h3>
              <div className="modal-actions">
                <button className="action-btn" onClick={handleExportConfig}>
                  {t('settings.importExport.exportConfig')}
                </button>
                <label className="action-btn">
                  {t('settings.importExport.importConfig')}
                  <input
                    type="file"
                    accept=".json"
                    onChange={handleImportConfig}
                    style={{ display: 'none' }}
                  />
                </label>
                <button className="action-btn secondary" onClick={() => setShowImportExport(false)}>
                  {t('settings.importExport.cancel')}
                </button>
              </div>
            </div>
          </div>
        )}

        <div className="settings-footer">
          <div className="version-info">{t('settings.footer.version', { version: '0.1.0' })}</div>
          <button className="reset-btn" onClick={() => {
            setLanguage('en');
            setTheme('dark');
            setFontSize(14);
            setOpacity(0.85);
            setAlwaysOnTop(true);
            setAutoStart(false);
            setNotifications(true);
            setSound(true);
            setSoundVolume(0.7);
            setHttpPort(31415);
            setCustomColors({ primaryColor: '', backgroundColor: '', textColor: '' });
            setReminderThreshold(100);
            setDoNotDisturb(false);
            setDoNotDisturbStart('22:00');
            setDoNotDisturbEnd('08:00');
          }}>
            {t('settings.footer.resetDefaults')}
          </button>
        </div>
      </>
    );
  }
}

// src/components/SettingsPanel.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useProgressStore } from '../stores/progressStore';
import LanguageSelector from './LanguageSelector.vue';
import './SettingsPanel.css';

interface Props {
  isStandalone?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  isStandalone: true,
});

const emit = defineEmits<{
  close: [];
}>();

const { t } = useI18n();
const store = useProgressStore();

type TabType = 'general' | 'appearance' | 'notifications' | 'tasks' | 'shortcuts';
const activeTab = ref<TabType>('general');
const showImportExport = ref(false);

const themes = ['dark', 'light', 'purple', 'ocean', 'forest', 'midnight'] as const;

function handleExportConfig() {
  const config = {
    settings: {
      theme: store.settings.theme,
      opacity: store.settings.opacity,
      alwaysOnTop: store.settings.alwaysOnTop,
      notifications: store.settings.notifications,
      sound: store.settings.sound,
      soundVolume: store.settings.soundVolume,
      httpPort: store.settings.httpPort,
      customColors: store.settings.customColors,
      reminderThreshold: store.settings.reminderThreshold,
      doNotDisturb: store.settings.doNotDisturb,
      doNotDisturbStart: store.settings.doNotDisturbStart,
      doNotDisturbEnd: store.settings.doNotDisturbEnd,
    },
    history: store.history.slice(0, 20),
    exportedAt: new Date().toISOString(),
  };

  const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'vibe-progress-config.json';
  a.click();
  URL.revokeObjectURL(url);
  showImportExport.value = false;
}

function handleImportConfig(event: Event) {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = (e) => {
    try {
      const config = JSON.parse(e.target?.result as string);
      if (config.settings) {
        if (config.settings.theme) store.setTheme(config.settings.theme);
        if (config.settings.fontSize) store.setFontSize(config.settings.fontSize);
        if (config.settings.opacity) store.setOpacity(config.settings.opacity);
        if (config.settings.alwaysOnTop !== undefined) store.setAlwaysOnTop(config.settings.alwaysOnTop);
        if (config.settings.notifications !== undefined) store.setNotifications(config.settings.notifications);
        if (config.settings.sound !== undefined) store.setSound(config.settings.sound);
        if (config.settings.soundVolume) store.setSoundVolume(config.settings.soundVolume);
        if (config.settings.httpPort) store.setHttpPort(config.settings.httpPort);
        if (config.settings.customColors) store.setCustomColors(config.settings.customColors);
        if (config.settings.reminderThreshold) store.setReminderThreshold(config.settings.reminderThreshold);
        if (config.settings.doNotDisturb !== undefined) store.setDoNotDisturb(config.settings.doNotDisturb);
        if (config.settings.doNotDisturbStart) store.setDoNotDisturbStart(config.settings.doNotDisturbStart);
        if (config.settings.doNotDisturbEnd) store.setDoNotDisturbEnd(config.settings.doNotDisturbEnd);
      }
      showImportExport.value = false;
    } catch {
      alert('Failed to import configuration. Please check the file format.');
    }
  };
  reader.readAsText(file);
}

function handleResetDefaults() {
  store.setLanguage('en');
  store.setTheme('dark');
  store.setFontSize(14);
  store.setOpacity(0.85);
  store.setAlwaysOnTop(true);
  store.setAutoStart(false);
  store.setNotifications(true);
  store.setSound(true);
  store.setSoundVolume(0.7);
  store.setHttpPort(31415);
  store.setCustomColors({ primaryColor: '', backgroundColor: '', textColor: '' });
  store.setReminderThreshold(100);
  store.setDoNotDisturb(false);
  store.setDoNotDisturbStart('22:00');
  store.setDoNotDisturbEnd('08:00');
}
</script>

<template>
  <div :class="['settings-panel', { standalone: isStandalone }]" @click.stop>
    <!-- Header for overlay mode -->
    <div v-if="!isStandalone" class="settings-header">
      <h2>{{ t('settings.title') }}</h2>
      <button class="close-btn" @click="emit('close')">×</button>
    </div>

    <!-- Tabs -->
    <div class="settings-tabs">
      <button :class="['tab', { active: activeTab === 'general' }]" @click="activeTab = 'general'">
        {{ t('settings.tabs.general') }}
      </button>
      <button :class="['tab', { active: activeTab === 'appearance' }]" @click="activeTab = 'appearance'">
        {{ t('settings.tabs.appearance') }}
      </button>
      <button :class="['tab', { active: activeTab === 'notifications' }]" @click="activeTab = 'notifications'">
        {{ t('settings.tabs.notifications') }}
      </button>
      <button :class="['tab', { active: activeTab === 'tasks' }]" @click="activeTab = 'tasks'">
        {{ t('settings.tabs.tasks') }}
      </button>
      <button :class="['tab', { active: activeTab === 'shortcuts' }]" @click="activeTab = 'shortcuts'">
        {{ t('settings.tabs.shortcuts') }}
      </button>
    </div>

    <!-- Content -->
    <div class="settings-content">
      <!-- General Tab -->
      <div v-if="activeTab === 'general'" class="settings-section">
        <div class="setting-item">
          <label>{{ t('settings.general.language') }}</label>
          <LanguageSelector />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.general.alwaysOnTop') }}</label>
          <input type="checkbox" :checked="store.settings.alwaysOnTop" @change="store.setAlwaysOnTop(($event.target as HTMLInputElement).checked)" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.general.autoStart') }}</label>
          <input type="checkbox" :checked="store.settings.autoStart" @change="store.setAutoStart(($event.target as HTMLInputElement).checked)" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.general.httpPort') }}</label>
          <input type="number" :value="store.settings.httpPort" @change="store.setHttpPort(parseInt(($event.target as HTMLInputElement).value))" min="1024" max="65535" class="port-input" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.general.importExport') }}</label>
          <button class="action-btn small" @click="showImportExport = true">
            {{ t('settings.general.manage') }}
          </button>
        </div>
      </div>

      <!-- Appearance Tab -->
      <div v-if="activeTab === 'appearance'" class="settings-section">
        <div class="setting-item">
          <label>{{ t('settings.appearance.theme') }}</label>
          <select :value="store.settings.theme" @change="store.setTheme(($event.target as HTMLSelectElement).value as any)" class="theme-select">
            <option v-for="theme in themes" :key="theme" :value="theme">
              {{ t(`settings.appearance.themes.${theme}`) }}
            </option>
          </select>
        </div>
        <div class="setting-item">
          <label>{{ t('settings.appearance.fontSize', { size: store.settings.fontSize }) }}</label>
          <input type="range" :value="store.settings.fontSize" @input="store.setFontSize(parseInt(($event.target as HTMLInputElement).value))" min="10" max="24" step="1" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.appearance.opacity', { percentage: Math.round(store.settings.opacity * 100) }) }}</label>
          <input type="range" :value="store.settings.opacity" @input="store.setOpacity(parseFloat(($event.target as HTMLInputElement).value))" min="0.3" max="1" step="0.05" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.appearance.primaryColor') }}</label>
          <div class="color-input-wrapper">
            <input type="color" :value="store.settings.customColors.primaryColor || '#6366f1'" @input="store.setCustomColors({ primaryColor: ($event.target as HTMLInputElement).value })" class="color-input" />
            <input type="text" class="color-text-input" :value="store.settings.customColors.primaryColor || ''" @input="store.setCustomColors({ primaryColor: ($event.target as HTMLInputElement).value })" placeholder="#6366f1" />
          </div>
        </div>
        <div class="setting-item">
          <label>{{ t('settings.appearance.resetColors') }}</label>
          <button class="action-btn small" @click="store.setCustomColors({ primaryColor: '', backgroundColor: '', textColor: '' })">
            {{ t('settings.appearance.reset') }}
          </button>
        </div>
      </div>

      <!-- Notifications Tab -->
      <div v-if="activeTab === 'notifications'" class="settings-section">
        <div class="setting-item">
          <label>{{ t('settings.notifications.desktopNotifications') }}</label>
          <input type="checkbox" :checked="store.settings.notifications" @change="store.setNotifications(($event.target as HTMLInputElement).checked)" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.notifications.soundAlerts') }}</label>
          <input type="checkbox" :checked="store.settings.sound" @change="store.setSound(($event.target as HTMLInputElement).checked)" />
        </div>
        <div v-if="store.settings.sound" class="setting-item indent">
          <label>{{ t('settings.notifications.volume', { percentage: Math.round(store.settings.soundVolume * 100) }) }}</label>
          <input type="range" :value="store.settings.soundVolume" @input="store.setSoundVolume(parseFloat(($event.target as HTMLInputElement).value))" min="0" max="1" step="0.1" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.notifications.completionThreshold', { percentage: store.settings.reminderThreshold }) }}</label>
          <input type="range" :value="store.settings.reminderThreshold" @input="store.setReminderThreshold(parseInt(($event.target as HTMLInputElement).value))" min="50" max="100" step="5" />
        </div>
        <div class="setting-item">
          <label>{{ t('settings.notifications.doNotDisturb') }}</label>
          <input type="checkbox" :checked="store.settings.doNotDisturb" @change="store.setDoNotDisturb(($event.target as HTMLInputElement).checked)" />
        </div>
        <template v-if="store.settings.doNotDisturb">
          <div class="setting-item indent">
            <label>{{ t('settings.notifications.startTime') }}</label>
            <input type="time" :value="store.settings.doNotDisturbStart" @input="store.setDoNotDisturbStart(($event.target as HTMLInputElement).value)" class="time-input" />
          </div>
          <div class="setting-item indent">
            <label>{{ t('settings.notifications.endTime') }}</label>
            <input type="time" :value="store.settings.doNotDisturbEnd" @input="store.setDoNotDisturbEnd(($event.target as HTMLInputElement).value)" class="time-input" />
          </div>
        </template>
      </div>

      <!-- Tasks Tab -->
      <div v-if="activeTab === 'tasks'" class="settings-section">
        <div class="setting-item">
          <label>{{ t('settings.tasks.history') }}</label>
          <span class="info-text">{{ t('settings.tasks.historyCount', { count: store.history.length }) }}</span>
        </div>
        <div class="setting-item">
          <label>{{ t('settings.tasks.clearHistory') }}</label>
          <button class="action-btn danger small" @click="store.clearHistory">
            {{ t('settings.tasks.clear') }}
          </button>
        </div>
      </div>

      <!-- Shortcuts Tab -->
      <div v-if="activeTab === 'shortcuts'" class="settings-section">
        <div class="shortcuts-info">
          <h4>{{ t('settings.shortcuts.title') }}</h4>
          <p>{{ t('settings.shortcuts.description') }}</p>
          <div class="shortcut-list">
            <div class="shortcut-item">
              <span class="shortcut-key">{{ t('settings.shortcuts.rightClick') }}</span>
              <span class="shortcut-desc">Open context menu</span>
            </div>
            <div class="shortcut-item">
              <span class="shortcut-key">{{ t('settings.shortcuts.drag') }}</span>
              <span class="shortcut-desc">Move window</span>
            </div>
            <div class="shortcut-item">
              <span class="shortcut-key">{{ t('settings.shortcuts.scroll') }}</span>
              <span class="shortcut-desc">Adjust progress</span>
            </div>
            <div class="shortcut-item">
              <span class="shortcut-key">{{ t('settings.shortcuts.clickStatus') }}</span>
              <span class="shortcut-desc">Activate IDE window</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Import/Export Modal -->
    <div v-if="showImportExport" class="import-export-modal">
      <div class="modal-content">
        <h3>{{ t('settings.importExport.title') }}</h3>
        <div class="modal-actions">
          <button class="action-btn" @click="handleExportConfig">
            {{ t('settings.importExport.exportConfig') }}
          </button>
          <label class="action-btn">
            {{ t('settings.importExport.importConfig') }}
            <input type="file" accept=".json" @change="handleImportConfig" style="display: none" />
          </label>
          <button class="action-btn secondary" @click="showImportExport = false">
            {{ t('settings.importExport.cancel') }}
          </button>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="settings-footer">
      <div class="version-info">{{ t('settings.footer.version', { version: '0.1.0' }) }}</div>
      <button class="reset-btn" @click="handleResetDefaults">
        {{ t('settings.footer.resetDefaults') }}
      </button>
    </div>
  </div>
</template>
