// src/App.tsx
import { useEffect, useRef, useState, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import './utils/i18n';
import { StatusText } from './components/StatusText';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { invoke } from '@tauri-apps/api/core';
import { useProgressStore, ProgressTask } from './stores/progressStore';
import { useProgressNotifications } from './hooks/useProgressEvent';
import { SHORTCUTS, registerGlobalShortcut, moveToCorner } from './utils/windowManager';
import { debug, error } from './utils/logger';
import './App.css';

debug('App.tsx loaded');

// IDE 窗口类型
interface IdeWindow {
  bundle_id: string;
  ide: string;
  window_title: string;
  window_index: number;
}

function App() {
  const { t } = useTranslation();
  const { tasks, currentTaskId, settings, setCurrentTask, updateProgress, resetTask, removeTask, syncFromHttpApi } = useProgressStore();
  const containerRef = useRef<HTMLDivElement>(null);
  const [showMenu, setShowMenu] = useState(false);
  const [isResizing, setIsResizing] = useState(false);
  const [completedTask, setCompletedTask] = useState<string | null>(null);
  const [, forceUpdate] = useState(0); // For time updates
  const [clickedCompletedTasks, setClickedCompletedTasks] = useState<Set<string>>(new Set()); // Track clicked completed tasks
  const [isCollapsed, setIsCollapsed] = useState(false); // Start expanded
  const [isCollapseTransition, setIsCollapseTransition] = useState(false); // Skip auto-resize during collapse
  const prevTasksRef = useRef<typeof tasks>([]);
  const [ideWindows, setIdeWindows] = useState<IdeWindow[]>([]); // IDE 窗口列表

  useProgressNotifications();

  // 扫描 IDE 窗口
  const scanIdeWindows = useCallback(async () => {
    try {
      const windows = await invoke<IdeWindow[]>('get_ide_windows');
      debug('Scanned IDE windows', { count: windows.length, windows });
      setIdeWindows(windows);
    } catch (err) {
      error('Failed to scan IDE windows', { error: String(err) });
    }
  }, []);

  // 启动时扫描 IDE 窗口，并定期刷新
  useEffect(() => {
    scanIdeWindows();
    const interval = setInterval(scanIdeWindows, 5000); // 每 5 秒刷新一次
    return () => clearInterval(interval);
  }, [scanIdeWindows]);

  // 合并 API 任务和 IDE 窗口
  // API 任务优先（有状态信息），IDE 窗口作为补充
  const allDisplayItems = [...tasks];

  // 将 IDE 窗口转换为任务格式（如果没有对应的 API 任务）
  ideWindows.forEach(win => {
    const existingTask = tasks.find(t =>
      t.ide === win.ide &&
      (t.windowTitle === win.window_title || win.window_title.includes(t.windowTitle || ''))
    );
    if (!existingTask) {
      // 创建一个虚拟任务来显示 IDE 窗口
      const virtualTask: ProgressTask = {
        id: `ide_${win.ide}_${win.window_index}`,
        name: win.window_title,
        progress: 0,
        tokens: 0,
        status: 'idle',
        startTime: 0,
        ide: win.ide,
        windowTitle: win.window_title,
      };
      allDisplayItems.push(virtualTask);
    }
  });

  // Sort tasks to prevent jumping
  // Primary sort by IDE type, secondary sort by window title/name
  allDisplayItems.sort((a, b) => {
    const ideA = a.ide || '';
    const ideB = b.ide || '';
    if (ideA !== ideB) {
      return ideA.localeCompare(ideB);
    }
    const nameA = a.windowTitle || a.name || '';
    const nameB = b.windowTitle || b.name || '';
    return nameA.localeCompare(nameB);
  });

  const displayTasks = allDisplayItems.filter(t => t.status === 'completed' || t.status === 'running' || t.status === 'idle' || t.status === 'armed' || t.status === 'active' || t.status === 'registered');
  const currentTask = tasks.find(t => t.id === currentTaskId) || tasks.find(t => t.status === 'running') || displayTasks[0] || null;

  // Detect newly completed tasks
  useEffect(() => {
    const prevTasks = prevTasksRef.current;
    tasks.forEach(task => {
      const prevTask = prevTasks.find(t => t.id === task.id);
      if (prevTask && prevTask.status !== 'completed' && task.status === 'completed') {
        // Task just completed - show notification
        setCompletedTask(task.id);
        setTimeout(() => setCompletedTask(null), 3000);
      }
    });
    prevTasksRef.current = [...tasks];
  }, [tasks]);

  // Dynamically resize window based on task count and collapse state
  useEffect(() => {
    // Skip auto-resize during collapse transition (handled manually)
    if (isCollapseTransition) return;

    const resizeWindow = async () => {
      const taskCount = displayTasks.length;
      const taskHeight = 36;
      const padding = 20;

      let newHeight = padding;
      if (taskCount === 0) {
        newHeight = 60;
      } else if (taskCount === 1) {
        newHeight = 70;
      } else {
        newHeight = padding + taskCount * taskHeight;
      }

      const width = isCollapsed ? 120 : 280;

      try {
        await invoke('resize_window', { width, height: Math.max(50, newHeight) });
      } catch (e) {
        error('Failed to resize window', { error: String(e) });
      }
    };
    resizeWindow();
  }, [displayTasks.length, isCollapsed, isCollapseTransition]);

  useEffect(() => {
    debug('App mounted', { taskCount: tasks.length, taskName: currentTask?.name });
  }, [tasks, currentTask]);

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', settings.theme);
    document.documentElement.style.setProperty('--app-font-size', `${settings.fontSize}px`);
  }, [settings.theme, settings.fontSize]);

  useEffect(() => {
    if (settings.customColors.primaryColor) {
      document.documentElement.style.setProperty('--primary-color', settings.customColors.primaryColor);
    }
    if (settings.customColors.backgroundColor) {
      document.documentElement.style.setProperty('--bg-color', settings.customColors.backgroundColor);
    }
    if (settings.customColors.textColor) {
      document.documentElement.style.setProperty('--text-color', settings.customColors.textColor);
    }
  }, [settings.customColors]);

  useEffect(() => {
    const syncInterval = setInterval(() => {
      syncFromHttpApi();
      forceUpdate(n => n + 1); // Update time display
    }, 1000);

    return () => clearInterval(syncInterval);
  }, [syncFromHttpApi]);

  useEffect(() => {
    const unregisterShortcuts = [
      registerGlobalShortcut(SHORTCUTS.TOGGLE_ALWAYS_ON_TOP, async () => {
        await invoke('toggle_window_always_on_top');
      }),
      registerGlobalShortcut(SHORTCUTS.RESET_PROGRESS, () => {
        if (currentTask) {
          resetTask(currentTask.id);
        }
      }),
      registerGlobalShortcut(SHORTCUTS.NEXT_TASK, () => {
        if (tasks.length > 1) {
          const currentIndex = tasks.findIndex(t => t.id === currentTaskId);
          const nextIndex = (currentIndex + 1) % tasks.length;
          setCurrentTask(tasks[nextIndex].id);
        }
      }),
      registerGlobalShortcut(SHORTCUTS.PREV_TASK, () => {
        if (tasks.length > 1) {
          const currentIndex = tasks.findIndex(t => t.id === currentTaskId);
          const prevIndex = (currentIndex - 1 + tasks.length) % tasks.length;
          setCurrentTask(tasks[prevIndex].id);
        }
      }),
      registerGlobalShortcut(SHORTCUTS.SHOW_MENU, () => {
        setShowMenu(prev => !prev);
      }),
    ];

    return () => {
      unregisterShortcuts.forEach(unregister => unregister());
    };
  }, [tasks, currentTaskId, currentTask, setCurrentTask, resetTask]);

  const handleMouseDown = async (e: React.MouseEvent) => {
    if (e.button === 0) {
      if (isResizing) return;
      // Don't start dragging if clicking on interactive elements
      const target = e.target as HTMLElement;
      if (target.closest('.task-row') || target.closest('.collapsed-task-item') || target.closest('.collapse-btn') || target.closest('button')) {
        return;
      }
      await getCurrentWindow().startDragging();
    }
  };

  const handleResizeStart = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsResizing(true);

    const startX = e.clientX;
    const startY = e.clientY;
    const container = containerRef.current;
    if (!container) return;

    const startWidth = container.offsetWidth;
    const startHeight = container.offsetHeight;

    const handleMouseMove = (moveEvent: MouseEvent) => {
      const newWidth = Math.max(150, Math.min(400, startWidth + (moveEvent.clientX - startX)));
      const newHeight = Math.max(50, Math.min(150, startHeight + (moveEvent.clientY - startY)));
      container.style.width = `${newWidth}px`;
      container.style.height = `${newHeight}px`;
    };

    const handleMouseUp = () => {
      setIsResizing(false);
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
    };

    document.addEventListener('mousemove', handleMouseMove);
    document.addEventListener('mouseup', handleMouseUp);
  };

  const handleRightClick = (e: React.MouseEvent) => {
    e.preventDefault();
    setShowMenu(!showMenu);
  };

  // @ts-ignore - handleProgressChange may be used in future
  const handleProgressChange = (_value: number) => {
    if (currentTask) {
      updateProgress(currentTask.id, _value);
    }
  };

  const handleTaskSelect = (taskId: string) => {
    setCurrentTask(taskId);
    setShowMenu(false);
  };

  const handleDeleteTask = (taskId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    removeTask(taskId);
    setShowMenu(false);
  };

  const handleResetTask = () => {
    if (currentTask) {
      resetTask(currentTask.id);
    }
    setShowMenu(false);
  };

  const handleOpenSettings = () => {
    setShowMenu(false);
    window.dispatchEvent(new CustomEvent('open-settings'));
  };

  const handleMoveToCorner = (corner: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right') => {
    moveToCorner(corner);
    setShowMenu(false);
  };

  const handleWheelProgress = (e: React.WheelEvent) => {
    if (currentTask) {
      const delta = e.deltaY > 0 ? -5 : 5;
      const newProgress = Math.max(0, Math.min(100, currentTask.progress + delta));
      updateProgress(currentTask.id, newProgress);
    }
  };

  const handleActivateWindow = async () => {
    if (currentTask) {
      // Use activate_ide_window for all IDEs (AppleScript-based window activation)
      if (currentTask.ide) {
        try {
          await invoke('activate_ide_window', {
            ide: currentTask.ide,
            windowTitle: currentTask.windowTitle || null,
            projectPath: currentTask.projectPath || null,
            activeFile: currentTask.activeFile || null  // 用于窗口匹配
          });
          debug('IDE window activated', { ide: currentTask.ide, windowTitle: currentTask.windowTitle, projectPath: currentTask.projectPath, activeFile: currentTask.activeFile });
        } catch (err) {
          error('Failed to activate IDE window', { error: String(err), ide: currentTask.ide });
        }
      }
    }
  };

  const handleTaskClick = async (task: typeof currentTask) => {
    if (!task) return;
    debug('Task clicked', { taskId: task.id, ide: task.ide, windowTitle: task.windowTitle, projectPath: task.projectPath, activeFile: task.activeFile });
    setCurrentTask(task.id);

    if (task.status === 'completed') {
      setClickedCompletedTasks(prev => new Set([...prev, task.id]));
    }

    // Use activate_ide_window for all IDEs (AppleScript-based window activation)
    if (task.ide) {
      try {
        debug('Activating IDE window', { ide: task.ide, windowTitle: task.windowTitle, projectPath: task.projectPath, activeFile: task.activeFile });
        await invoke('activate_ide_window', {
          ide: task.ide,
          windowTitle: task.windowTitle || null,
          projectPath: task.projectPath || null,
          activeFile: task.activeFile || null  // 用于窗口匹配
        });
        debug('IDE window activated successfully', { ide: task.ide });
      } catch (err) {
        error('Failed to activate IDE window', { error: String(err), ide: task.ide });
      }
    } else {
      debug('No IDE specified for task', { taskId: task.id });
    }
  };

  // Handle collapse/expand with right-align position adjustment
  const handleCollapse = async () => {
    const expandedWidth = 280;
    const collapsedWidth = 120;
    const widthDiff = expandedWidth - collapsedWidth;

    // Prevent auto-resize during transition
    setIsCollapseTransition(true);

    try {
      const win = getCurrentWindow();
      const position = await win.innerPosition();
      const scaleFactor = await win.scaleFactor();

      // Convert physical pixels to logical pixels
      const logicalX = position.x / scaleFactor;
      const logicalY = position.y / scaleFactor;

      // Calculate height
      const taskCount = displayTasks.length;
      const taskHeight = 36;
      const padding = 20;
      let newHeight = padding;
      if (taskCount === 0) {
        newHeight = 60;
      } else if (taskCount === 1) {
        newHeight = 70;
      } else {
        newHeight = padding + taskCount * taskHeight;
      }
      newHeight = Math.max(50, newHeight);

      if (!isCollapsed) {
        // Collapsing: resize to smaller width, then move right
        await invoke('resize_window', { width: collapsedWidth, height: newHeight });
        const newX = logicalX + widthDiff;
        await invoke('set_window_position', { x: newX, y: logicalY });
      } else {
        // Expanding: move left first, then resize to larger width
        const newX = logicalX - widthDiff;
        await invoke('set_window_position', { x: newX, y: logicalY });
        await invoke('resize_window', { width: expandedWidth, height: newHeight });
      }

      setIsCollapsed(!isCollapsed);
    } catch (e) {
      error('Failed to adjust window position', { error: String(e) });
      setIsCollapsed(!isCollapsed);
    } finally {
      // Re-enable auto-resize after a short delay
      setTimeout(() => setIsCollapseTransition(false), 100);
    }
  };

  return (
    <div
      ref={containerRef}
      className={`app-container ${completedTask ? 'has-completed' : ''} ${displayTasks.length > 1 ? 'multi-task' : ''} ${isCollapsed ? 'collapsed' : ''}`}
      onMouseDown={handleMouseDown}
      onContextMenu={handleRightClick}
      onWheel={handleWheelProgress}
      style={{ opacity: settings.opacity }}
    >
      {/* Collapsed view - narrow bar on right side */}
      {isCollapsed ? (
        <div className="collapsed-view">
          {/* Expand button on left - same position as collapse button */}
          <button className="collapse-btn expanded" onClick={handleCollapse}>‹</button>
          <div className="collapsed-content">
            <div className="collapsed-tasks">
              {displayTasks.length === 0 ? (
                <div className="collapsed-empty">◆</div>
              ) : (
                displayTasks.map(task => (
                  <div key={task.id} className={`collapsed-task-item ${task.status}`} onClick={() => handleTaskClick(task)}>
                    <span className="collapsed-status">
                      {task.status === 'running' ? '◉' : task.status === 'completed' ? '✓' : task.status === 'armed' ? '◎' : task.status === 'active' ? '◈' : task.status === 'registered' ? '◇' : '○'}
                    </span>
                    <span className="collapsed-task-name">{task.name?.substring(0, 8) || task.ide}</span>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      ) : (
        <>
          {/* Collapse button on left */}
          <button className="collapse-btn" onClick={handleCollapse}>›</button>

          {/* Show completed notification */}
          {completedTask && (
            <div className="completed-banner">
              ✓ {t('notification.taskCompleted', { taskName: tasks.find(t => t.id === completedTask)?.name || t('menu.title') })}
            </div>
          )}

          {/* Multi-task view */}
          {displayTasks.length > 1 ? (
            <div className="multi-task-list">
              {displayTasks.map((task) => {
                // Calculate elapsed time (only for running/completed, not armed/active/registered)
                let timeStr = '';
                if (task.status === 'armed') {
                  timeStr = '⏳'; // Armed: waiting for AI activity
                } else if (task.status === 'active') {
                  timeStr = '👁'; // Active: window has focus
                } else if (task.status === 'registered') {
                  timeStr = '◇'; // Registered: waiting for AI activity
                } else if (task.status === 'completed') {
                  const elapsed = (task.endTime || Date.now()) - task.startTime;
                  const minutes = Math.floor(elapsed / 60000);
                  const seconds = Math.floor((elapsed % 60000) / 1000);
                  timeStr = minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`;
                } else if (task.status === 'running' && task.startTime > 0) {
                  const elapsed = Date.now() - task.startTime;
                  const minutes = Math.floor(elapsed / 60000);
                  const seconds = Math.floor((elapsed % 60000) / 1000);
                  timeStr = minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`;
                }

                const isClickedCompleted = task.status === 'completed' && clickedCompletedTasks.has(task.id);
                const showHighlight = task.status === 'completed' && !isClickedCompleted;

                return (
                  <div
                    key={task.id}
                    className={`task-row ${task.id === currentTaskId ? 'active' : ''} ${showHighlight ? 'completed' : ''} ${isClickedCompleted ? 'completed-clicked' : ''} ${task.status === 'armed' ? 'armed' : ''} ${task.status === 'active' ? 'active-state' : ''}`}
                    onClick={() => handleTaskClick(task)}
                  >
                    <span className={`mini-status status-${task.status}`}>
                      {task.status === 'running' ? '◉' : task.status === 'completed' ? '✓' : task.status === 'armed' ? '◎' : task.status === 'active' ? '◈' : task.status === 'registered' ? '◇' : '○'}
                    </span>
                    <span className="task-name-mini">{task.name}</span>
                    <span className={`task-time-mini ${task.status === 'completed' ? 'completed-time' : ''} ${task.status === 'armed' ? 'armed-time' : ''} ${task.status === 'active' ? 'active-time' : ''}`}>
                      {task.status === 'completed' ? `✓ ${timeStr}` : timeStr}
                    </span>
                    {task.ide && <span className="ide-badge-mini">{t(`ide.${task.ide.toLowerCase().replace(/\s+/g, '-')}`) !== `ide.${task.ide.toLowerCase().replace(/\s+/g, '-')}` ? t(`ide.${task.ide.toLowerCase().replace(/\s+/g, '-')}`) : task.ide}</span>}
                  </div>
                );
              })}
            </div>
          ) : (
            /* Single task view */
            <>
              {displayTasks.length === 0 ? (
                <div className="app-header">
                  <span className="app-icon">{t('app.icon')}</span>
                  <span className="app-title">{t('app.title')}</span>
                </div>
              ) : (() => {
                // Calculate elapsed time for single task (not for armed/active)
                const task = currentTask;
                let elapsedTime: string | undefined;
                if (task) {
                  if (task.status === 'armed') {
                    elapsedTime = '⏳'; // Armed: waiting
                  } else if (task.status === 'active') {
                    elapsedTime = '👁'; // Active: window has focus
                  } else if (task.status === 'completed') {
                    const elapsed = (task.endTime || Date.now()) - task.startTime;
                    const minutes = Math.floor(elapsed / 60000);
                    const seconds = Math.floor((elapsed % 60000) / 1000);
                    elapsedTime = minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`;
                  } else if (task.startTime > 0) {
                    const elapsed = Date.now() - task.startTime;
                    const minutes = Math.floor(elapsed / 60000);
                    const seconds = Math.floor((elapsed % 60000) / 1000);
                    elapsedTime = minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`;
                  }
                }
                return (
                  <StatusText
                    taskName={currentTask?.name || ''}
                    status={currentTask?.status || 'idle'}
                    tokens={currentTask?.tokens || 0}
                    ide={currentTask?.ide}
                    onActivate={handleActivateWindow}
                    elapsedTime={elapsedTime}
                  />
                );
              })()}
            </>
          )}

          <div className="resize-handle" onMouseDown={handleResizeStart}></div>
          {showMenu && (
            <div className="context-menu" onClick={(e) => e.stopPropagation()}>
              <div className="menu-header">{t('menu.title')}</div>
              {tasks.length === 0 ? (
                <div className="menu-item disabled">{t('menu.noTasks')}</div>
              ) : (
                tasks.map(task => (
                  <div
                    key={task.id}
                    className={`menu-item ${task.id === currentTaskId ? 'active' : ''}`}
                    onClick={() => handleTaskSelect(task.id)}
                  >
                    <span className={`status-dot status-${task.status}`}></span>
                    <span className="task-name">{task.name}</span>
                    <span className="task-progress">{task.progress}%</span>
                    <button
                      className="delete-btn"
                      onClick={(e) => handleDeleteTask(task.id, e)}
                    >
                      ×
                    </button>
                  </div>
                ))
              )}
              <div className="menu-divider"></div>
              <div className="menu-item" onClick={handleResetTask}>
                {t('menu.resetTask')}
              </div>
              <div className="menu-item submenu">
                <span>{t('menu.position')}</span>
                <div className="submenu-content">
                  <div className="menu-item" onClick={() => handleMoveToCorner('top-left')}>{t('menu.topLeft')}</div>
                  <div className="menu-item" onClick={() => handleMoveToCorner('top-right')}>{t('menu.topRight')}</div>
                  <div className="menu-item" onClick={() => handleMoveToCorner('bottom-left')}>{t('menu.bottomLeft')}</div>
                  <div className="menu-item" onClick={() => handleMoveToCorner('bottom-right')}>{t('menu.bottomRight')}</div>
                </div>
              </div>
              <div className="menu-item" onClick={handleOpenSettings}>
                {t('menu.settings')}
              </div>
              <div className="menu-item" onClick={() => setShowMenu(false)}>
                {t('menu.closeMenu')}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useProgressStore, type ProgressTask } from './stores/progressStore';
import StatusText from './components/StatusText.vue';
import SettingsPanel from './components/SettingsPanel.vue';
import { debug, error } from './utils/logger';

debug('App.vue loaded');

// Check if we're running in Tauri
const isTauri = typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;

// Safe wrappers for Tauri APIs
async function safeInvoke<T>(cmd: string, args?: Record<string, unknown>): Promise<T | null> {
  if (!isTauri) return null;
  const { invoke } = await import('@tauri-apps/api/core');
  return invoke<T>(cmd, args);
}

async function getCurrentWindowLabel(): Promise<string> {
  if (!isTauri) return 'main';
  const { getCurrentWindow } = await import('@tauri-apps/api/window');
  return getCurrentWindow().label;
}

async function getWindow() {
  if (!isTauri) return null;
  const { getCurrentWindow } = await import('@tauri-apps/api/window');
  return getCurrentWindow();
}

// Check if this is the settings window
const isSettingsWindow = ref(false);
getCurrentWindowLabel().then(label => {
  isSettingsWindow.value = label === 'settings';
  debug('Window label', { label, isSettings: isSettingsWindow.value });
});

interface IdeWindow {
  bundle_id: string;
  ide: string;
  window_title: string;
  window_index: number;
}

const { t } = useI18n();
const store = useProgressStore();

// Reactive state
const containerRef = ref<HTMLDivElement | null>(null);
const showMenu = ref(false);
const completedTask = ref<string | null>(null);
const clickedCompletedTasks = ref<Set<string>>(new Set());
const seenActiveTasks = ref<Set<string>>(new Set());
const isCollapsed = ref(false);
const isCollapseTransition = ref(false);
const ideWindows = ref<IdeWindow[]>([]);
const prevTasks = ref<ProgressTask[]>([]);
const isActivatingRef = ref(false);

// Computed
const allDisplayItems = computed(() => {
  const items = [...store.tasks];
  
  ideWindows.value.forEach(win => {
    const existingTask = store.tasks.find(t =>
      t.ide === win.ide &&
      (t.windowTitle === win.window_title || win.window_title.includes(t.windowTitle || ''))
    );
    if (!existingTask) {
      const virtualTask: ProgressTask = {
        id: `ide_${win.ide}_${win.window_index}`,
        name: win.window_title,
        progress: 0,
        tokens: 0,
        status: 'idle',
        startTime: 0,
        ide: win.ide,
        windowTitle: win.window_title,
      };
      items.push(virtualTask);
    }
  });

  // Sort by IDE then name for stable order
  items.sort((a, b) => {
    const ideA = a.ide || '';
    const ideB = b.ide || '';
    if (ideA !== ideB) return ideA.localeCompare(ideB);
    const nameA = a.windowTitle || a.name || '';
    const nameB = b.windowTitle || b.name || '';
    return nameA.localeCompare(nameB);
  });

  return items;
});

const displayTasks = computed(() =>
  allDisplayItems.value.filter(t =>
    ['completed', 'running', 'armed', 'idle'].includes(t.status)
  )
);

const currentTask = computed(() =>
  store.tasks.find(t => t.id === store.currentTaskId) ||
  store.tasks.find(t => t.status === 'running') ||
  displayTasks.value[0] || null
);

// Scan IDE windows
async function scanIdeWindows() {
  try {
    const windows = await safeInvoke<IdeWindow[]>('get_ide_windows');
    if (windows) {
      debug('Scanned IDE windows', { count: windows.length });
      ideWindows.value = windows;
    }
  } catch (err) {
    error('Failed to scan IDE windows', { error: String(err) });
  }
}

// Handle task click
function handleTaskClick(task: ProgressTask) {
  debug('Task clicked', { taskId: task.id });
  store.setCurrentTask(task.id);
}

// Handle task double click - navigate to IDE
async function handleTaskDoubleClick(task: ProgressTask) {
  if (isActivatingRef.value) return;
  isActivatingRef.value = true;
  debug('Task double-clicked', { taskId: task.id, ide: task.ide });

  if (task.status === 'completed') {
    clickedCompletedTasks.value = new Set([...clickedCompletedTasks.value, task.id]);
  }

  if (task.ide) {
    try {
      await safeInvoke('activate_ide_window', {
        ide: task.ide,
        windowTitle: task.windowTitle || null,
        projectPath: task.projectPath || null,
        activeFile: task.activeFile || null
      });
    } catch (err) {
      error('Failed to activate IDE window', { error: String(err) });
    } finally {
      setTimeout(() => { isActivatingRef.value = false; }, 500);
    }
  } else {
    isActivatingRef.value = false;
  }
}

// Handle collapse/expand
async function handleCollapse() {
  const expandedWidth = 280;
  const collapsedWidth = 120;
  const widthDiff = expandedWidth - collapsedWidth;

  isCollapseTransition.value = true;

  try {
    const win = await getWindow();
    if (!win) {
      isCollapsed.value = !isCollapsed.value;
      return;
    }
    const position = await win.innerPosition();
    const scaleFactor = await win.scaleFactor();

    const logicalX = position.x / scaleFactor;
    const logicalY = position.y / scaleFactor;

    const currentSize = await win.innerSize();
    const currentHeight = Math.round(currentSize.height / scaleFactor);

    if (!isCollapsed.value) {
      await safeInvoke('resize_window', { width: collapsedWidth, height: currentHeight });
      await safeInvoke('set_window_position', { x: logicalX + widthDiff, y: logicalY });
    } else {
      await safeInvoke('set_window_position', { x: logicalX - widthDiff, y: logicalY });
      await safeInvoke('resize_window', { width: expandedWidth, height: currentHeight });
    }

    isCollapsed.value = !isCollapsed.value;
  } catch (e) {
    error('Failed to adjust window position', { error: String(e) });
    isCollapsed.value = !isCollapsed.value;
  } finally {
    setTimeout(() => { isCollapseTransition.value = false; }, 100);
  }
}

// Open settings
async function handleOpenSettings() {
  setShowMenu(false);
  try {
    await safeInvoke('open_settings_window');
  } catch (err) {
    error('Failed to open settings', { error: String(err) });
  }
}

function setShowMenu(value: boolean) {
  showMenu.value = value;
}

// Handle mouse down for window dragging
async function handleMouseDown(event: MouseEvent) {
  // Only start drag if clicking on the container itself (not buttons or interactive elements)
  const target = event.target as HTMLElement;
  if (target.closest('button') || target.closest('.task-row') || target.closest('.menu-item') || target.closest('.context-menu')) {
    return;
  }
  try {
    const win = await getWindow();
    if (win) {
      await win.startDragging();
    }
  } catch {
    // Ignore drag errors
  }
}

// Get time string for task
function getTimeStr(task: ProgressTask): string {
  // Focused window shows eye icon
  if (task.isFocused) return '👁';
  if (task.status === 'armed') return '⏳';
  if (task.status === 'completed' && task.startTime > 0) {
    const elapsed = (task.endTime || Date.now()) - task.startTime;
    const minutes = Math.floor(elapsed / 60000);
    const seconds = Math.floor((elapsed % 60000) / 1000);
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
  }
  if (task.status === 'running' && task.startTime > 0) {
    const elapsed = Date.now() - task.startTime;
    const minutes = Math.floor(elapsed / 60000);
    const seconds = Math.floor((elapsed % 60000) / 1000);
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
  }
  return '';
}

// Get status icon - checks isFocused first, then status
function getStatusIcon(task: ProgressTask): string {
  // Focused window shows eye icon regardless of status
  if (task.isFocused) return '◈';
  switch (task.status) {
    case 'running': return '◉';
    case 'completed': return '✓';
    case 'armed': return '◎';
    default: return '○';
  }
}

// Track running/focused tasks and detect completions
watch(() => store.tasks, (newTasks) => {
  // Track focused/running tasks
  newTasks.forEach(task => {
    if (task.isFocused || task.status === 'running') {
      seenActiveTasks.value = new Set([...seenActiveTasks.value, task.id]);
    }
  });

  // Detect completions
  newTasks.forEach(task => {
    const prevTask = prevTasks.value.find(t => t.id === task.id);
    if (prevTask && prevTask.status !== 'completed' && task.status === 'completed') {
      if (!seenActiveTasks.value.has(task.id)) {
        completedTask.value = task.id;
        setTimeout(() => { completedTask.value = null; }, 3000);
      }
      if (seenActiveTasks.value.has(task.id)) {
        clickedCompletedTasks.value = new Set([...clickedCompletedTasks.value, task.id]);
      }
    }
  });

  prevTasks.value = [...newTasks];
}, { deep: true });

// Dynamic window resize
watch([displayTasks, isCollapsed, isCollapseTransition], async () => {
  if (isCollapseTransition.value) return;

  const taskCount = displayTasks.value.length;
  const taskHeight = 36;
  const padding = 20;

  let newHeight = padding;
  if (taskCount === 0) {
    newHeight = 60;
  } else if (taskCount === 1) {
    newHeight = 70;
  } else {
    newHeight = padding + taskCount * taskHeight;
  }

  const width = isCollapsed.value ? 120 : 280;

  try {
    await safeInvoke('resize_window', { width, height: Math.max(50, newHeight) });
  } catch (e) {
    error('Failed to resize window', { error: String(e) });
  }
});

// Intervals
let syncInterval: number;
let scanInterval: number;
let forceUpdateInterval: number;

onMounted(async () => {
  // Initial scan
  await scanIdeWindows();
  await store.syncFromHttpApi();

  // Set up intervals
  syncInterval = window.setInterval(() => store.syncFromHttpApi(), 1000);
  scanInterval = window.setInterval(scanIdeWindows, 5000);
  forceUpdateInterval = window.setInterval(() => {}, 1000); // Force update for time
});

onUnmounted(() => {
  clearInterval(syncInterval);
  clearInterval(scanInterval);
  clearInterval(forceUpdateInterval);
});
</script>

<template>
  <!-- Settings Window -->
  <div v-if="isSettingsWindow" class="settings-window-container">
    <SettingsPanel :is-standalone="true" />
  </div>

  <!-- Main Window -->
  <div
    v-else
    ref="containerRef"
    :class="['app-container', { collapsed: isCollapsed, 'multi-task': displayTasks.length > 1, 'has-completed': !!completedTask }]"
    :style="{ opacity: store.settings.opacity }"
    @mousedown="handleMouseDown"
  >
    <!-- Collapse/Expand button -->
    <button
      :class="['collapse-btn', { expanded: isCollapsed }]"
      @click="handleCollapse"
    >
      {{ isCollapsed ? '‹' : '›' }}
    </button>

    <!-- Completed notification -->
    <div v-if="completedTask" class="completed-banner">
      ✓ {{ t('notification.taskCompleted', { taskName: store.tasks.find(t => t.id === completedTask)?.name || t('menu.title') }) }}
    </div>

    <!-- Multi-task view -->
    <div v-if="displayTasks.length > 1" class="multi-task-list">
      <div
        v-for="task in displayTasks"
        :key="task.id"
        :class="[
          'task-row',
          { active: task.id === store.currentTaskId },
          { completed: task.status === 'completed' && !clickedCompletedTasks.has(task.id) },
          { 'completed-clicked': clickedCompletedTasks.has(task.id) },
          { armed: task.status === 'armed' },
          { 'focused-state': task.isFocused }
        ]"
        @click="handleTaskClick(task)"
        @dblclick="handleTaskDoubleClick(task)"
      >
        <span :class="['mini-status', `status-${task.status}`]">
          {{ getStatusIcon(task) }}
        </span>
        <span class="task-name-mini">{{ task.name }}</span>
        <span :class="['task-time-mini', { 'completed-time': task.status === 'completed', 'armed-time': task.status === 'armed', 'focused-time': task.isFocused }]">
          {{ task.status === 'completed' ? `✓ ${getTimeStr(task)}` : getTimeStr(task) }}
        </span>
        <span v-if="task.ide" class="ide-badge-mini">{{ task.ide }}</span>
      </div>
    </div>

    <!-- Single task view -->
    <template v-else>
      <div v-if="displayTasks.length === 0" class="app-header">
        <span class="app-icon">{{ t('app.icon') }}</span>
        <span class="app-title">{{ t('app.title') }}</span>
      </div>
      <StatusText
        v-else-if="currentTask"
        :status="currentTask.status"
        :name="currentTask.name"
        :is-focused="currentTask.isFocused"
        :elapsed-time="getTimeStr(currentTask)"
        :show-icon="true"
      />
    </template>

    <!-- Context menu -->
    <div v-if="showMenu" class="context-menu">
      <div class="menu-item" @click="handleOpenSettings">
        {{ t('menu.settings') }}
      </div>
      <div class="menu-item" @click="setShowMenu(false)">
        {{ t('menu.closeMenu') }}
      </div>
    </div>
  </div>
</template>
